version: "3.2"
services:
    database:
        container_name: database
        image: mariadb
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        environment:
            - TZ=Asia/Seoul
            - MYSQL_DATABASE=stove
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_ROOT_HOST=%
        restart: always
        ports:
            - 3306:3306

    spring:
        container_name: spring
        build: ./server
        ports:
            - 8080:8080
        volumes:
            - /server
        depends_on:
            - database
        restart: always

    nginx:
        container_name: nginx
        environment:
            - TZ="Asia/Seoul"
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - spring
        volumes:
            - /nginx/
